# Generated by Django 5.0.1 on 2024-02-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('SUMMER', 'Summer'), ('WINTER', 'Winter'), ('MONSOON', 'Monsoon')], max_length=10)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
