# Generated by Django 5.0.2 on 2024-02-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_cart_date_added_alter_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
